server:
    host: 127.0.0.1
    port: 50051
    cert_file: ../tls/server.pem
    cert_key_file: ../tls/server.key
    ca_file: ../tls/ca.pem
repository:
    host: localhost
    port: 5432
    user: fim
    Password: fim
    db_name: fim
    timezone: Europe/Berlin
